### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by hkniberg** [faradayio/flight#2]
Hi! This looks absolutely awesome! We are looking for something like this to integrate with travel sights sites, to help travellers make better decisions. But this looks like it isn't active, judging from the lack of commits. What's the status of this project? Is it dead? If so, what would it take to wake it up again? Or is there something else more active that fulfills the same need?

**Comment by rossmeissl** [comment]
Hi @hkniberg it was awesome, thanks :) Unfortunately Brighter Planet CM1 and the associated open source emitter projects like this one are no longer supported. But we leave them open source in the hopes that you can gain value from them!
